import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./(auth)/context";
import Notification from "./components/toast";
import { Footer } from "./home/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Career",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <AuthProvider>
                <Notification />
                <body className={inter.className}>{children}</body>
            </AuthProvider>
            {/* <Footer /> */}
        </html>

    );
}
